name: sudo_sql_builder
description: SQL Builder for dart
version: 1.0.0
homepage: https://sudo.dog

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
